<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PetEmulator.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>PetEmulator.Cli.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="System.CommandLine" />
    <ProjectReference Include="../PetEmulator.Pet/PetEmulator.Pet.csproj" />
    <ProjectReference Include="../../lib/PetEmulator.Debugger/PetEmulator.Debugger.csproj" />
    <ProjectReference Include="../PetEmulator.Vic20/PetEmulator.Vic20.csproj" />
    <ProjectReference Include="../PetEmulator.Trs80/PetEmulator.Trs80.csproj" />
    <ProjectReference Include="../PetEmulator.Cpc464/PetEmulator.Cpc464.csproj" />
    <ProjectReference Include="../../lib/PetEmulator.CpuZ80/PetEmulator.CpuZ80.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
