<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>PetEmulator.Vic20.Cartridge.Rtc</RootNamespace>
    <AssemblyName>PetEmulator.Vic20.Cartridge.Rtc</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../lib/PetEmulator.Chips/PetEmulator.Chips.csproj" />
    <ProjectReference Include="../../lib/PetEmulator.Vic20.Cartridge.Abstractions/PetEmulator.Vic20.Cartridge.Abstractions.csproj" />
  </ItemGroup>
</Project>
