<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>PetEmulator.Cpu6502.Tests</RootNamespace>
    <NoWarn>$(NoWarn);CS0618;CS0652;CS8602</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="FluentAssertions" />
    <ProjectReference Include="../../lib/PetEmulator.Cpu6502/PetEmulator.Cpu6502.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Data/*.bin" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Data/*.nes" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Data/*.log" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
