<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>PetEmulator.Cpu6809.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="FluentAssertions" />
    <ProjectReference Include="../../lib/PetEmulator.Cpu6809/PetEmulator.Cpu6809.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TestData/schwotzer-cputest.bin" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
