<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>PetEmulator.Core.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="FluentAssertions" />
    <ProjectReference Include="../../lib/PetEmulator.Core/PetEmulator.Core.csproj" />
    <ProjectReference Include="../../src/PetEmulator.Pet/PetEmulator.Pet.csproj" />
    <ProjectReference Include="../../src/PetEmulator.Vic20/PetEmulator.Vic20.csproj" />
    <ProjectReference Include="../../src/PetEmulator.Kaypro/PetEmulator.Kaypro.csproj" />
    <ProjectReference Include="../../src/PetEmulator.Trs80/PetEmulator.Trs80.csproj" />
    <ProjectReference Include="../../src/PetEmulator.Cpc464/PetEmulator.Cpc464.csproj" />
    <ProjectReference Include="../../src/PetEmulator.Cpc6128/PetEmulator.Cpc6128.csproj" />
  </ItemGroup>
</Project>
