<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>PetEmulator.Cpu6809</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../PetEmulator.Cpu6800/PetEmulator.Cpu6800.csproj" />
    <ProjectReference Include="../PetEmulator.Core/PetEmulator.Core.csproj" />
  </ItemGroup>
</Project>
