<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>PetEmulator.CpuZ80</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../PetEmulator.Core/PetEmulator.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
