<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PetEmulator.Screenshot</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Avalonia.Skia" />
    <ProjectReference Include="../PetEmulator.Desktop/PetEmulator.Desktop.csproj" />
  </ItemGroup>
</Project>
