<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>PetEmulator.Cpc464</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../lib/PetEmulator.Core/PetEmulator.Core.csproj" />
    <ProjectReference Include="../../lib/PetEmulator.Chips/PetEmulator.Chips.csproj" />
    <ProjectReference Include="../../lib/PetEmulator.CpuZ80/PetEmulator.CpuZ80.csproj" />
  </ItemGroup>
</Project>
